name: fludoku
description: A package for generating and solving Sudoku boards.
version: 1.0.0
repository: https://github.com/raulcostajunior/fludoku

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  fixnum: ^1.1.0
